# Kinematic generator
This notebook converts a Denavit Hartenberg table to its direct kinematic symbolic calculation and its jacobian

In [45]:
from cmath import pi
import numpy as np
import sympy
# from sympy.abc import x,y,z,a,d
from kinematicBuilder import *

# import sys
# sys.set_int_max_str_digits(0)

# Examples

## 3 DOF Cartesian 
A 3 DOF Cartesian robot with 3 prismatic joints from [The Ultimate Guide to Jacobian Matrices for Robotics](https://automaticaddison.com/the-ultimate-guide-to-jacobian-matrices-for-robotics/)

In [46]:
T1 = DenavitRow(pi/2,   0, 0, pi/2,  Joint(sympy.Symbol('q_1'),JointType.PRISMATIC))
T2 = DenavitRow(pi/2,   0, 0, -pi/2, Joint(sympy.Symbol('q_2'),JointType.PRISMATIC))
T3 = DenavitRow(0,      0, 0, 0,     Joint(sympy.Symbol('q_3'),JointType.PRISMATIC))

T_cartesian = DenavitDK((T1,T2,T3),"Cartesian")

In [47]:
T_cartesian.inversePositionEval([0,0,0],[1,2,3])

0.0


array([ 3.,  1., -2.])

In [48]:
# T_cartesian.genURDF()

In [49]:
cartesian = T_cartesian.jacobian * T_cartesian.jointsSym
cartesian

Matrix([
[ q_2],
[-q_3],
[ q_1],
[   0],
[   0],
[   0]])

In [50]:
joint_values = (0, 0, 0)
T_cartesian.eval(joint_values)

array([[ 0, -1,  0,  0],
       [ 0,  0, -1,  0],
       [ 1,  0,  0,  0],
       [ 0,  0,  0,  1]])

## 3 DOF Articulated Robot
A 3 DOF Articulated robot with 3 rotational joints from [The Ultimate Guide to Jacobian Matrices for Robotics](https://automaticaddison.com/the-ultimate-guide-to-jacobian-matrices-for-robotics/)

In [51]:
T1 = DenavitRow(0,  1.5, 0,   pi/2, Joint(sympy.Symbol('q_1'),JointType.ROTATIONAL))
T2 = DenavitRow(0,  0,  1,  0,    Joint(sympy.Symbol('q_2'),JointType.ROTATIONAL))
T3 = DenavitRow(0,  0,  0.5,  0,    Joint(sympy.Symbol('q_3'),JointType.ROTATIONAL))

T_articular3 = DenavitDK((T1,T2,T3))

In [52]:
joint_values = (0, 0, 0)
T_articular3.eval(joint_values)

array([[ 1. , -0. ,  0. ,  1.5],
       [ 0. , -0. , -1. ,  0. ],
       [ 0. ,  1. ,  0. ,  1.5],
       [ 0. ,  0. ,  0. ,  1. ]])

## 6 DOF articular
A 6 DOF articular robot that follows the following scheme: 
<!-- ![axes](axes_diagram.png) -->
<img src="axes_diagram.png" alt="axes_diagram" width="400"/>

In [53]:
L = [0.2, 1, 1, 0.2]
T1 = DenavitRow(0,      L[0],   0,      pi/2,   Joint(sympy.Symbol('q_1'),JointType.ROTATIONAL))
T2 = DenavitRow(pi/2,   0,      L[1],   0,      Joint(sympy.Symbol('q_2'),JointType.ROTATIONAL))
T3 = DenavitRow(pi,     0,      0,      pi/2,   Joint(sympy.Symbol('q_3'),JointType.ROTATIONAL))
# T_ = DenavitRow(pi/2,   0.02,       0,      pi/2)
T4 = DenavitRow(pi,     L[2],   0,      pi/2,   Joint(sympy.Symbol('q_4'),JointType.ROTATIONAL))
T5 = DenavitRow(pi,     0,      0,      pi/2,   Joint(sympy.Symbol('q_5'),JointType.ROTATIONAL))
T6 = DenavitRow(0,      L[3],   0,      0,      Joint(sympy.Symbol('q_6'),JointType.ROTATIONAL))

T_articular6 = DenavitDK((T1,T2,T3,T4,T5,T6))
T_articular6.directTransformSym

Matrix([
[(((-sin(q_2 + 884279719003555/562949953421312)*sin(q_3 + 884279719003555/281474976710656)*cos(q_1) + cos(q_1)*cos(q_2 + 884279719003555/562949953421312)*cos(q_3 + 884279719003555/281474976710656))*cos(q_4 + 884279719003555/281474976710656) + sin(q_1)*sin(q_4 + 884279719003555/281474976710656))*cos(q_5 + 884279719003555/281474976710656) + (sin(q_2 + 884279719003555/562949953421312)*cos(q_1)*cos(q_3 + 884279719003555/281474976710656) + sin(q_3 + 884279719003555/281474976710656)*cos(q_1)*cos(q_2 + 884279719003555/562949953421312))*sin(q_5 + 884279719003555/281474976710656))*cos(q_6) + ((-sin(q_2 + 884279719003555/562949953421312)*sin(q_3 + 884279719003555/281474976710656)*cos(q_1) + cos(q_1)*cos(q_2 + 884279719003555/562949953421312)*cos(q_3 + 884279719003555/281474976710656))*sin(q_4 + 884279719003555/281474976710656) - sin(q_1)*cos(q_4 + 884279719003555/281474976710656))*sin(q_6), -(((-sin(q_2 + 884279719003555/562949953421312)*sin(q_3 + 884279719003555/281474976710656)*cos(q_

In [54]:
# T_articular6.genURDF()
# T_articular6.genCCode()

In [55]:
pose = T_articular6.eval((1,1,1,1,1,1))
pose

array([[ 0.21667169, -0.26112258,  0.94067443, -0.04166873],
       [-0.95867353, -0.23890322,  0.1545002 , -0.32699789],
       [ 0.18438665, -0.93527549, -0.30209487, -0.2294141 ],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])

In [56]:
T_articular6.inverseEval([0,0,0,0,0,0],pose)

0.5303672509456662
0.133090897045223
0.19805321952668054
0.058096235857168416
0.017616481038508602
0.0009623456241789342
1.7876297332903563e-06
18.1211469665257
2.144665599089547
0.25126644087095346
0.003841054137820905
8.995987686442113e-07
Solution with error 8.995987686442113e-07 with 995 iterations left


array([[4.14111614],
       [5.28242959],
       [2.14099392],
       [4.14151468],
       [0.99935058],
       [0.99891701]])

## 6 DOF robot with transformations in between

In [57]:
Lv = 50
T1 = DenavitRow(0,      0,          0,     -pi/2,   Joint(sympy.Symbol('q_1'),JointType.ROTATIONAL,upper_limit=pi/2,lower_limit=-pi/2))
T2 = DenavitRow(0,      0,          Lv,     0,      Joint(sympy.Symbol('q_2'),JointType.ROTATIONAL))
T3 = DenavitRow(0,      -0.0425,    Lv,     pi/2,   Joint(sympy.Symbol('q_3'),JointType.ROTATIONAL))
T_ = DenavitRow(pi/2,   0.02,       0,      pi/2)
T4 = DenavitRow(pi/2,   0,          0,      pi/2,   Joint(sympy.Symbol('q_4'),JointType.ROTATIONAL))
T5 = DenavitRow(pi/2,   0,          0,      pi/2,   Joint(sympy.Symbol('q_5'),JointType.ROTATIONAL))
T6 = DenavitRow(0,      0,          0,      0,      Joint(sympy.Symbol('q_6'),JointType.ROTATIONAL))
TCP = DenavitRow(0,     0,          10,     0)

T_walter = DenavitDK((T1,T2,T3,T_,T4,T5,T6,TCP),"Walter")

In [58]:
# T_walter.genURDF()
# T_walter.genCCode()